Repository qexat/PyVism, pull requests merged in 2023-02, with the labels that each got.

#6 GH-4: Make `flush` supporting more streams than `stdout`
  src/pyvism/runtime/builtins.py
  src/pyvism/vm.py
Labels: enhancement

#9 Enhance "unknown symbol" error message
  examples/wrong_symbol.vism
  src/pyvism/compiler.py
  src/pyvism/constants.py
Labels: enhancement

#18 GH-16: Add typed bytecode specialization
  src/pyvism/compiler.py
  src/pyvism/instructions.py
Labels: enhancement

#19 Change indentation to tabs
  setup.py
  src/pyvism/__main__.py
  src/pyvism/cli.py
  src/pyvism/compiler.py
  src/pyvism/constants.py
  src/pyvism/instructions.py
  src/pyvism/repl.py
  src/pyvism/runtime/builtins.py
  src/pyvism/runtime/errors.py
  src/pyvism/runtime/utils.py
  src/pyvism/vm.py
Labels: code style

#23 GH-22: Add contributing notice
  README.md
Labels: documentation

#25 GH-24: Use unused parameter
  src/pyvism/cli.py
Labels: enhancement

#20 Minor improvements
  README.md
  src/pyvism/compiler.py
  src/pyvism/instructions.py
  src/pyvism/runtime/builtins.py
Labels: enhancement, code style

#27 GH-26: Fix boolean trap
  src/pyvism/runtime/errors.py
Labels: enhancement, code style

#31 GH-30: Move contributing notice to separate file
  .github/CONTRIBUTING.md
  README.md
Labels: quality: enhancement, topic: meta

#33 GH-32: Improved list concatenation consistency
  src/pyvism/runtime/errors.py
Labels: quality: enhancement, topic: code style

#35 GH-34: Add `type: ignore` to false positive type error
  src/pyvism/runtime/errors.py
Labels: quality: workaround

#37 GH-36: Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: quality: enhancement, topic: meta

#39 Rewrite completely the architecture
  .gitignore
  .pre-commit-config.yaml
  CODE_OF_CONDUCT.md
  examples/addition.vism
  examples/err_typing_showcase.vism
  examples/err_wrong_symbol.vism
  examples/hello_world.vism
  examples/ok_addition.vism
  examples/ok_hello_world.vism
  examples/strong_typing.vism
  examples/wrong_symbol.vism
  setup.cfg
  src/pyvism/backend/__init__.py
  src/pyvism/backend/instructions.py
  src/pyvism/backend/interface.py
  src/pyvism/backend/tools.py
  src/pyvism/cli.py
  src/pyvism/compiler.py
  src/pyvism/compiler/__init__.py
  src/pyvism/compiler/compiler.py
  src/pyvism/compiler/internal.py
  src/pyvism/compiler/macros.py
  src/pyvism/compiler/tools.py
  src/pyvism/compiler/typechecking.py
  src/pyvism/compiler/types.py
  src/pyvism/constants.py
  src/pyvism/errsys/__init__.py
  src/pyvism/errsys/errors.py
  src/pyvism/errsys/tools.py
  src/pyvism/errsys/tricks.py
  src/pyvism/frontend/__init__.py
  src/pyvism/frontend/map.py
  src/pyvism/frontend/tools.py
  src/pyvism/frontend/vmbc/__init__.py
  src/pyvism/frontend/vmbc/frontend.py
  src/pyvism/frontend/vmbc/instructions.py
  src/pyvism/frontend/vmbc/tools.py
  src/pyvism/instructions.py
  src/pyvism/parser/__init__.py
  src/pyvism/parser/tools.py
  src/pyvism/py_utils.py
  src/pyvism/qtheme.py
  src/pyvism/repl.py
  src/pyvism/repl/__init__.py
  src/pyvism/repl/commands.py
  src/pyvism/repl/posix.py
  src/pyvism/repl/repl.py
  src/pyvism/repl/tools.py
  src/pyvism/repl/universal.py
  src/pyvism/runtime/builtins.py
  src/pyvism/runtime/utils.py
  src/pyvism/vm.py
  src/pyvism/vm/__init__.py
  src/pyvism/vm/runner.py
  src/pyvism/vm/vm.py
Labels: quality: enhancement, topic: code style, topic: meta, topic: design: compiler, topic: design: REPL, topic: design: VM, topic: design: CLI

#42 GH-40: Add input EOFError handling
  src/pyvism/errsys/errors.py
  src/pyvism/errsys/tools.py
  src/pyvism/repl/repl.py
Labels: quality: enhancement, topic: design: REPL (UNI)

#44 GH-43: Code cleaning + dead code removal
  src/pyvism/backend/interface.py
  src/pyvism/backend/tools.py
  src/pyvism/compiler/compiler.py
  src/pyvism/compiler/macros.py
  src/pyvism/frontend/vmbc/instructions.py
  src/pyvism/parser/tools.py
  src/pyvism/repl/posix.py
  src/pyvism/repl/universal.py
Labels: quality: enhancement, topic: code style

#45 Code cleaning + add comments
  src/pyvism/backend/instructions.py
  src/pyvism/backend/interface.py
  src/pyvism/backend/tools.py
  src/pyvism/cli.py
  src/pyvism/compiler/compiler.py
  src/pyvism/compiler/internal.py
  src/pyvism/compiler/macros.py
  src/pyvism/compiler/tools.py
  src/pyvism/compiler/types.py
  src/pyvism/constants.py
  src/pyvism/errsys/errors.py
  src/pyvism/errsys/tools.py
  src/pyvism/errsys/tricks.py
  src/pyvism/frontend/map.py
  src/pyvism/frontend/tools.py
  src/pyvism/frontend/vmbc/__init__.py
  src/pyvism/frontend/vmbc/instructions.py
  src/pyvism/frontend/vmbc/tools.py
  src/pyvism/parser/tools.py
  src/pyvism/repl/commands.py
  src/pyvism/repl/repl.py
  src/pyvism/repl/tools.py
  src/pyvism/vm/runner.py
  src/pyvism/vm/vm.py
Labels: quality: enhancement, topic: code style

#50 GH-41: Add `Ctrl`+ `D` handling
  src/pyvism/py_utils.py
  src/pyvism/repl/posix.py
Labels: quality: enhancement, topic: design: REPL (POSIX)

#54 GH-52: Fix accidental type definition resetting
  src/pyvism/parser/tools.py
Labels: topic: design: compiler, topic: design: parser

#56 GH-55: Remove string mode
  src/pyvism/parser/tools.py
Labels: topic: dead code

#59 GH-58: Add installer + update README
  README.md
  install.sh
Labels: quality: enhancement, topic: design: CLI

#61 GH-60: Fix Python incompatibility in user-created venv
  install.sh
Labels: topic: installer

#63 GH-62: Fix incorrect error message specialization
  install.sh
Labels: quality: enhancement, topic: installer

#64 Fix typo
  install.sh
Labels: topic: typo, topic: installer
